version: '3.1'
services:
  app:
    image: 'employee-transfers-0.0.1'
    build: ./
    depends_on:
       - postgres17
    ports:
        - 8080:8080

  postgres17:
        image: postgres:17
        container_name: postgres17
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12345
          - POSTGRES_DB=postgres