version: '3.1'
services:
  app:
    image: 'employee-transfers-0.0.1:latest'
    build: ./
    depends_on:
       - postgres15
    ports:
        - 8089:8089

  postgres15:
        image: postgres
        container_name: postgres15
        ports:
          - "5435:5432"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12345
          - POSTGRES_DB=postgres