kind: Service
apiVersion: v1
metadata:
  name: employeetransfers-postgres-k8s
  labels:
    name: employeetransfers-postgres-k8s
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: employeetransfers-postgres-k8s
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeetransfers-postgres-k8s
spec:
  selector:
    matchLabels:
      app: employeetransfers-postgres-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: employeetransfers-postgres-k8s
    spec:
      containers:
        - name: employeetransfers-postgres-k8s
          image: kutalamohanprasad/employee-transfers-0.0.1:latest
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-cred # Secret Name
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD