apiVersion: v1
kind: Secret
metadata:
  name: postgres-cred
  namespace: default
  labels:
    app: employeetransfers-postgres-k8s
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIzNDU=
